source 'https://ruby.taobao.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'jquery-turbolinks'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'rack-cors', :require => 'rack/cors'

gem 'tinymce-rails-langs'

gem 'spree', path: '..'
gem 'spree_alipay', path: '../vendor/spree_alipay'
gem 'spree_auth_devise', path: '../vendor/spree_auth_devise'
gem 'spree_recently_viewed', path: '../vendor/spree_recently_viewed'
gem 'spree_address_book', path: '../vendor/spree_address_book'
gem 'spree_wishlist', path: '../vendor/spree_wishlist'
gem 'spree_variant_options', path: '../vendor/spree_variant_options'
gem 'spree_ajax_add_to_cart', path: '../vendor/spree_ajax_add_to_cart'
gem 'spree_product_zoom', path: '../vendor/spree_product_zoom'
gem 'spree_one_page_checkout', path: '../vendor/spree_one_page_checkout'
gem 'spree_multi_currency', path: '../vendor/spree_multi_currency'
gem 'spree_static_content', path: '../vendor/spree_static_content'
gem 'spree_editor', path: '../vendor/spree_editor'
gem 'spree_return_authorizations_frontend', path: '../vendor/spree_return_authorizations_frontend'

gem 'spree_gateway'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-1-stable'
# gem 'spree_editor', github: 'spree-contrib/spree_editor', branch: '3-1-stable'
#gem 'spree_email_to_friend', github: 'spree-contrib/spree_email_to_friend', ref: 'a4092bee14dae36af21db1c4a325de4710bbf582'

gem 'normalize-rails'

#### import excel
gem 'roo', '~> 2.5.1'
gem 'ruby-pinyin'

group :test, :development do
  gem 'bullet'
  gem 'pry-byebug'
  gem 'rack-mini-profiler'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

#####
group :production do
  gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"
end
