# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d91a8ba9dea6e4a46490c26a807d18e26dcd4ec19d7c8608d543fe01d5cb96a5663185fc2466a132df1ab9c01c0f496d0b66086a1cc8b554fbf323b2a7be527

test:
  secret_key_base: 75d5c2b4a6be7ede17620e6f8d155b5137d65fc8d1a7a7e5333ab20e814368e1669b13cf7a3ca9c2002a5422ae3d35666b6706155babad4458ebfdca438efe7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1238471283ui4h124807ydf7ssjkfhd
